= Panorama
:toc: left
:sectanchors:





[cols="1,1,1,1,1"]
|===
|Stars |Category |Name |Description |Link

|
|
|MetalLB
|MetalLB is a load-balancer implementation for bare metal Kubernetes clusters, using standard routing protocols
|https://github.com/metallb/metallb


|
|
|SpiderFoot
|open source intelligence (OSINT) automation tool
|https://github.com/smicallef/spiderfoot


|
|Pentesting
|Traitor
|Automatic Linux privesc via exploitation of low-hanging fruit e.g. gtfobins, pwnkit, dirty pipe, +w docker.sock 
|https://github.com/liamg/traitor


|
|APM
|Pinpoint
|APM, (Application Performance Management) tool for large-scale distributed systems. 
|https://github.com/pinpoint-apm/pinpoint


|⭐
|HTTP Proxy
|Hetty
|HTTP toolkit for security research
|https://hetty.xyz/docs/


|⭐
|
|cloudquery
|transforms your cloud infrastructure into queryable SQL tables for easy monitoring, governance and security
|https://github.com/cloudquery/cloudquery


|===




== Lists


.Monitoring 

[horizontal]
ElastAlert:: XXX
(https://elastalert.readthedocs.io/en/latest/)

.Frontend

[horizontal]
PrimeVue:: rich set of open source UI Components for Vue
(https://github.com/primefaces/primevue)

roughViz.js:: reusable JavaScript library for creating sketchy/hand-drawn styled charts in the browser
(https://github.com/jwilber/roughViz)


.Networking 

[horizontal]
Picosnitch:: Monitor network traffic per executable using BPF 
(https://github.com/elesiuta/picosnitch)

OpenSnitch:: GNU/Linux port of the Little Snitch application firewall 
(https://github.com/evilsocket/opensnitch)


.Testing 

[horizontal]

Drill:: Drill is an HTTP load testing application written in Rust 
(https://github.com/fcsonline/drill)


LitmusChaos:: Open Source Chaos Engineering Platform
(https://github.com/litmuschaos/litmus)


.Kubernetes

[horizontal]
sloop:: https://github.com/salesforce/sloop

.WIP

[horizontal]
Mistborn:: A secure platform for easily standing up and managing your own cloud services: including firewall, ad-blocking, and multi-factor WireGuard VPN access 
(https://gitlab.com/cyber5k/mistborn)

Kube-OVN:: cloud-native network orchestration system 
(https://github.com/kubeovn/kube-ovn)

cloudquery:: transforms your cloud infrastructure into queryable SQL tables for easy monitoring, governance and security 
(https://github.com/cloudquery/cloudquery)

dug:: powerful global DNS propagation checker +
(https://github.com/unfrl/dug)



Cloudron:: Complete solution for running apps on your own server
(https://www.cloudron.io/index.html)


RouteConverter:: The popular GPS conversion and editing tool 
(https://github.com/cpesch/RouteConverter)

snipe-it:: A free open source IT asset/license management system 
(https://github.com/snipe/snipe-it)

iTop:: A simple, web based IT Service Management tool 
(https://github.com/Combodo/iTop)





== Kubernetes tools

[cols="1,1,1,1"]
|===
|Name |Category |Description |Link

|kubectl-rolesum
|RBAC
|Summarize RBAC roles for the specified subject (ServiceAccount, User and Group)
|https://github.com/Ladicle/kubectl-rolesum


|kubectl-neat
|
|Clean up Kubernetes yaml and json output to make it readable 
|https://github.com/itaysk/kubectl-neat

|dbench
|Performance
|Benchmark Kubernetes persistent disk volumes with fio: Read/write IOPS, bandwidth MB/s and latency 
|https://github.com/leeliu/dbench

|kubernetes-diff-logger
|Monitoring
|Logs updates to Kubernetes Objects for storing and querying with Loki 
|https://github.com/grafana/kubernetes-diff-logger

|suspicious-pods
|
|
|https://github.com/edrevo/suspicious-pods

|Pixie
|Monitoring
|
|https://github.com/pixie-io/pixie

|xxx
|
|
|



|===


== Categorized (wip)





.FinOps

https://github.com/kubecost/opencost
your favorite open source cost monitoring tool for Kubernetes

https://www.infracost.io/


.Local Kubernetes Clusters

https://microk8s.io/
The lightweight Kubernetes

https://k3s.io/
The certified Kubernetes distribution built for IoT & Edge computing

https://github.com/k0sproject/k0s
k0s is an all-inclusive Kubernetes distribution, which is configured with all of the features needed to build a Kubernetes cluster and packaged as a single binary for ease of use.


.IT asset management






== Uncategorized


https://goauthentik.io/



https://github.com/espanso/espanso
 Cross-platform Text Expander written in Rust 




https://github.com/ncrocfer/whatportis



https://github.com/kellyjonbrazil/jc
CLI tool and python library that converts the output of popular command-line tools and file-types to JSON, YAML, or Dictionaries. This allows piping of output to tools like jq and simplifying automation scripts. 




https://www.pomerium.com/docs/install
https://github.com/oauth2-proxy/oauth2-proxy
https://github.com/dexidp/dex/
https://github.com/kuadrant/authorino

https://github.com/panva/jose


https://github.com/louislam/uptime-kuma


https://github.com/sullo/nikto


hexyl : is a simple hex viewer for the terminal
https://github.com/sharkdp/hexyl

pwru : is an eBPF-based tool for tracing network packets in the Linux kernel with advanced filtering capabilities
https://github.com/cilium/pwru
